FROM centos:7.5.1804

ENV container docker
MAINTAINER Daniel lee (jujumilk3@gmail.com)

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm
RUN yum -y install python36u python36u-libs python36u-devel python36u-pip

RUN yum -y install gcc gcc-c++ zlib-devel openssl openssl-devel sqlite sqlite-devel wget tree nginx vim


EXPOSE 80

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
